// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $UserView_FormController from "./islands/UserView/FormController.tsx";
import * as $UserView_InitialStep from "./islands/UserView/InitialStep.tsx";
import * as $UserView_Step1 from "./islands/UserView/Step1.tsx";
import * as $UserView_Step2 from "./islands/UserView/Step2.tsx";
import * as $UserView_Step3 from "./islands/UserView/Step3.tsx";
import * as $UserView_Step4 from "./islands/UserView/Step4.tsx";
import * as $UserView_Step5 from "./islands/UserView/Step5.tsx";
import * as $UserView_Step6 from "./islands/UserView/Step6.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/UserView/FormController.tsx": $UserView_FormController,
    "./islands/UserView/InitialStep.tsx": $UserView_InitialStep,
    "./islands/UserView/Step1.tsx": $UserView_Step1,
    "./islands/UserView/Step2.tsx": $UserView_Step2,
    "./islands/UserView/Step3.tsx": $UserView_Step3,
    "./islands/UserView/Step4.tsx": $UserView_Step4,
    "./islands/UserView/Step5.tsx": $UserView_Step5,
    "./islands/UserView/Step6.tsx": $UserView_Step6,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
